- hosts: localhost
  gather_facts: false
  vars_files:
    - ../group_vars/all/vault.yml
  tasks:
    - template:
        src: "../templates/secrets.auto.tfvars.j2"
        dest: "../../terraform/secrets.auto.tfvars"
